name = "XYPicker"
uuid = "8672ba75-6745-4d2b-8eca-02ca7407da7f"
authors = ["Yu-Chang YANG <yang.yc.allium@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
